spring:
  config:
    activate:
      on-profile:
        - mysql
  datasource:
    schema:
      - classpath:schema.sql
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/subway?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
handlebars:
  suffix: .html
  enabled: true
security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000